apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: mern-app
data:
  ATLAS_URI: mongodb://mongodb:27017/sample_traininig
  MONGO_URL: mongodb://mongodb:27017/sample_training
  MONGO_URI: mongodb://mongodb:27017/sample_training
