apiVersion: batch/v1
kind: CronJob
metadata:
  name: etl-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: etl
              image: swr.ap-southeast-3.myhuaweicloud.com/baykar-case/etl:v2
              envFrom:
                - configMapRef:
                    name: app-config
          imagePullSecrets:
            - name: swr-secret
          restartPolicy: OnFailure